src/Entity/Logements.php
<?php

namespace App\Entity;

use App\Repository\LogementsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Metadata\ApiResource;

#[ORM\Entity(repositoryClass: LogementsRepository::class)]
#[ApiResource]
class Logements
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column]
    private ?float $rating = null;

    #[ORM\Column]
    private ?int $capacity = null;

    #[ORM\Column]
    private ?int $chambres = null;

    #[ORM\Column]
    private ?int $superficie = null;

    #[ORM\OneToMany(mappedBy: 'id_logements', targetEntity: Photos::class,cascade: ["persist", "remove"])]
    private Collection $id_photos;

    #[ORM\Column]
    private ?int $rentalready = null;

    #[ORM\Column]
    private ?int $prixmoyen = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $descriptionlg = null;

    #[ORM\Column]
    private ?int $salledebains = null;

    #[ORM\Column(nullable: true)]
    private ?int $misenavant = null;

    #[ORM\Column(length: 255)]
    private ?string $arrondissements = null;

    #[ORM\Column]
    private ?int $nbpieces = null;

    public function __construct()
    {
        $this->id_photos = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getRating(): ?float
    {
        return $this->rating;
    }

    public function setRating(float $rating): static
    {
        $this->rating = $rating;

        return $this;
    }

    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    public function setCapacity(int $capacity): static
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getChambres(): ?int
    {
        return $this->chambres;
    }

    public function setChambres(int $chambres): static
    {
        $this->chambres = $chambres;

        return $this;
    }

    public function getSuperficie(): ?int
    {
        return $this->superficie;
    }

    public function setSuperficie(int $superficie): static
    {
        $this->superficie = $superficie;

        return $this;
    }

    /**
     * @return Collection<int, Photos>
     */
    public function getIdPhotos(): Collection
    {
        return $this->id_photos;
    }

    public function addIdPhoto(Photos $idPhoto): static
    {
        if (!$this->id_photos->contains($idPhoto)) {
            $this->id_photos->add($idPhoto);
            $idPhoto->setIdLogements($this);
        }

        return $this;
    }

    public function removeIdPhoto(Photos $idPhoto): static
    {
        if ($this->id_photos->removeElement($idPhoto)) {
            // set the owning side to null (unless already changed)
            if ($idPhoto->getIdLogements() === $this) {
                $idPhoto->setIdLogements(null);
            }
        }

        return $this;
    }

    public function getRentalready(): ?int
    {
        return $this->rentalready;
    }

    public function setRentalready(int $rentalready): static
    {
        $this->rentalready = $rentalready;

        return $this;
    }

    public function getPrixmoyen(): ?int
    {
        return $this->prixmoyen;
    }

    public function setPrixmoyen(int $prixmoyen): static
    {
        $this->prixmoyen = $prixmoyen;

        return $this;
    }

    public function getDescriptionlg(): ?string
    {
        return $this->descriptionlg;
    }

    public function setDescriptionlg(string $descriptionlg): static
    {
        $this->descriptionlg = $descriptionlg;

        return $this;
    }

    public function getSalledebains(): ?int
    {
        return $this->salledebains;
    }

    public function setSalledebains(int $salledebains): static
    {
        $this->salledebains = $salledebains;

        return $this;
    }

    public function getMisenavant(): ?int
    {
        return $this->misenavant;
    }

    public function setMisenavant(?int $misenavant): static
    {
        $this->misenavant = $misenavant;

        return $this;
    }

    public function getArrondissements(): ?string
    {
        return $this->arrondissements;
    }

    public function setArrondissements(string $arrondissements): static
    {
        $this->arrondissements = $arrondissements;

        return $this;
    }

    public function getNbpieces(): ?int
    {
        return $this->nbpieces;
    }

    public function setNbpieces(int $nbpieces): static
    {
        $this->nbpieces = $nbpieces;

        return $this;
    }

}

src/Form/LogementsType.php
<?php

namespace App\Form;

use App\Entity\Logements;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LogementsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre', TextType::class, [
                'label' => 'Titre de la propriété',
                'label_attr' => [
                    'class' => 'h3 mt-3',
                ],
                'attr' => [
                    'class' => 'form-control',
                ],
            ])
            ->add('description', TextType::class, [
                'label' => 'Description courte',
                'label_attr' => [
                    'class' => 'h3 mt-3',
                ],
                'attr' => [
                    'class' => 'form-control',
                ],
            ])
            ->add('descriptionlg', TextareaType::class, [
                'label' => 'Description longue',
                'label_attr' => [
                    'class' => 'h3 mt-3',
                ],
                'attr' => [
                    'class' => 'form-control',
                ],
            ])
            ->add('arrondissements', ChoiceType::class, [
                'label' => 'Arrondissements',
                'choices' => array_combine(range(1, 18), range(1, 18)) + ['Hors Paris' => 'Hors Paris'],
                'expanded' => false,
                'multiple' => false,
                'label_attr' => [
                    'class' => 'h3 mt-3',
                ],
                'attr' => [
                    'class' => 'form-select'
                ],
            ])
            ->add('rentalready', IntegerType::class, [
                'label' => 'Id Rental Ready',
                'label_attr' => [
                    'class' => 'h3 mt-3',
                ],
                'attr' => [
                    'class' => 'form-control',
                ],
            ])
            ->add('prixmoyen', IntegerType::class, [
                'label' => 'Prix Moyen',
                'label_attr' => [
                    'class' => 'h3 mt-3',
                ],
                'attr' => [
                    'class' => 'form-control',
                ],
            ])
            ->add('salledebains', IntegerType::class, [
                'label' => 'Nombre de salle de bain',
                'label_attr' => [
                    'class' => 'h3 mt-3',
                ],
                'attr' => [
                    'class' => 'form-control',
                ],
            ])
            ->add('rating', NumberType::class, [
                'label' => 'Note',
                'label_attr' => [
                    'class' => 'h3 mt-3',
                ],
                'attr' => [
                    'class' => 'form-control',
                    'step' => '0.1', // Définit le pas de l'input (permet les décimales)
                    'min' => '0',    // Note minimale
                    'max' => '5',   // Note maximale
                ],
            ])
            ->add('capacity', IntegerType::class, [
                'label' => 'Capacité accueil',
                'label_attr' => [
                    'class' => 'h3 mt-3',
                ],
                'attr' => [
                    'class' => 'form-control',
                ],
            ])
            ->add('nbpieces', IntegerType::class, [
                'label' => 'Nombre de pièces',
                'label_attr' => [
                    'class' => 'h3 mt-3',
                ],
                'attr' => [
                    'class' => 'form-control',
                ],
            ])
            ->add('chambres', IntegerType::class, [
                'label' => 'Nombre de chambre',
                'label_attr' => [
                    'class' => 'h3 mt-3',
                ],
                'attr' => [
                    'class' => 'form-control',
                ],
            ])
            ->add('superficie', IntegerType::class, [
                'label' => 'Superficie',
                'label_attr' => [
                    'class' => 'h3 mt-3',
                ],
                'attr' => [
                    'class' => 'form-control',
                ],
            ])
            ->add('misenavant', ChoiceType::class, [
                'label' => 'Mise en avant de l\'image (MAXIMUM 4 LOGEMENTS)',
                'choices' => [
                    'Oui' => 1,
                    'Non' => 0,
                ],
                'label_attr' => [
                    'class' => 'h3 mt-3',
                ],
                'expanded' => true, // Pour afficher les choix sous forme de boutons radio (utilisez 'false' pour une liste déroulante)
                'multiple' => false, // Utilisez 'true' si vous voulez autoriser plusieurs choix
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Logements::class,
        ]);
    }
}

src/Controller/LogementsController.php
<?php

namespace App\Controller;

use App\Entity\Logements;
use App\Form\LogementsType;
use App\Repository\LogementsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Vich\UploaderBundle\Templating\Helper\UploaderHelper;
use Knp\Component\Pager\PaginatorInterface;

#[Route('/logements')]
class LogementsController extends AbstractController
{
    #[Route('/', name: 'app_logements_index', methods: ['GET'])]
    public function index(LogementsRepository $logementsRepository, PaginatorInterface $paginator, Request $request): Response
    {
        $logements = $logementsRepository->findBy([], ['id' => 'DESC']);

        // Paginez les résultats
        $pagination = $paginator->paginate(
            $logements, // Requête contenant les données à paginer
            $request->query->getInt('page', 1), // Page par défaut
            8 // Nombre d'éléments par page
        );

        return $this->render('logements/index.html.twig', [
            'logements' => $pagination,
        ]);
    }
    #[Route('/misenavant', name: 'app_logements_mis_en_avant', methods: ['GET'])]
    public function logementsMisEnAvant(EntityManagerInterface $entityManager): Response
    {
        $logementsMisEnAvant = $entityManager->getRepository(Logements::class)
            ->findBy(['misenavant' => 1]);

        return $this->render('logements/mis_en_avant.html.twig', [
            'logements' => $logementsMisEnAvant,
        ]);
    }

    #[Route('/new', name: 'app_logements_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $logement = new Logements();
        $form = $this->createForm(LogementsType::class, $logement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($logement);
            $entityManager->flush();

            return $this->redirectToRoute('app_logements_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('logements/new.html.twig', [
            'logement' => $logement,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_logements_show', methods: ['GET'])]
    public function show(Logements $logement): Response
    {
        return $this->render('logements/show.html.twig', [
            'logement' => $logement,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_logements_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Logements $logement, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(LogementsType::class, $logement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_logements_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('logements/edit.html.twig', [
            'logement' => $logement,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_logements_delete', methods: ['POST'])]
    public function delete(Request $request, Logements $logement, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$logement->getId(), $request->request->get('_token'))) {
            $entityManager->remove($logement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_logements_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/logements/_delete_form.html.twig
<form method="post" action="{{ path('app_logements_delete', {'id': logement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ logement.id) }}">
    <button class="btn btn-danger mt-3 mb-3">Supprimer le logement</button>
</form>

templates/logements/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<button class="btn btn-primary mt-3 mb-3">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/logements/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Logements{% endblock %}

{% block body %}
    <div class="navbar">{% include ('/navbar/index.html.twig') %}</div>
    <div class="container">
        <h1>Edit Logements</h1>
        <div class="col-md-12"> {# Utilisez col-md-6 pour diviser la rangée en deux colonnes #}
            {{ include('logements/_form.html.twig', {'button_label': 'Update'}) }}
        </div>
        <div class="col-md-6"> {# Deuxième colonne #}
            {{ include('logements/_delete_form.html.twig') }}
        </div>
    </div>
{% endblock %}

templates/logements/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Logements index{% endblock %}

{% block body %}
    <div class="navbar">{% include ('/navbar/index.html.twig') %}</div>
    <div class="container">
        <h1>Logements index</h1>

        <table class="table">
            <thead>
            <tr>
                <th>Titre</th>
                <th>Description</th>
                <th>actions</th>
            </tr>
            </thead>
            <tbody>
            {% for logement in logements %}
                <tr>
                    <td>{{ logement.titre }}</td>
                    <td>{{ logement.description }}</td>
                    <td>
                        <a href="{{ path('app_logements_show', {'id': logement.id}) }}" class="btn btn-primary">show</a>
                        <a href="{{ path('app_logements_edit', {'id': logement.id}) }}" class="btn btn-warning">edit</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="9">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="navigation">
           {{ knp_pagination_render(logements) }}
        </div>
        <a href="{{ path('app_logements_new') }}" class="btn btn-primary">Ajouter un logement</a>
    </div>
{% endblock %}

templates/logements/mis_en_avant.html.twig
{% extends 'base.html.twig' %}

{% block title %}Logements index{% endblock %}

{% block body %}
    <div class="navbar">{% include ('/navbar/index.html.twig') %}</div>
    <div class="container">
        <h1>Logements Mis en Avant (Maximum 4)</h1>

        <table class="table">
            <thead>
            <tr>
                <th>Titre</th>
                <th>Description</th>
                <th>actions</th>
            </tr>
            </thead>
            <tbody>
            {% for logement in logements %}
                <tr>
                    <td>{{ logement.titre }}</td>
                    <td>{{ logement.description }}</td>
                    <td>
                        <a href="{{ path('app_logements_show', {'id': logement.id}) }}" class="btn btn-primary">show</a>
                        <a href="{{ path('app_logements_edit', {'id': logement.id}) }}" class="btn btn-warning">edit</a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="9">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/logements/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Logements{% endblock %}

{% block body %}
    <div class="navbar">{% include ('/navbar/index.html.twig') %}</div>
    <div class="container">
        <h1>Nouveau Logement</h1>

        {{ include('logements/_form.html.twig') }}

    </div>
{% endblock %}

templates/logements/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Logements{% endblock %}

{% block body %}
    <div class="navbar">{% include ('/navbar/index.html.twig') %}</div>
    <div class="container">
        <h1>Logements</h1>

        <div class="row">
            <div class="col-md-6">
                <h2>Informations du Logement</h2>
                <table class="table table-striped">
                    <tbody>
                    <tr>
                        <th>Id</th>
                        <td>{{ logement.id }}</td>
                    </tr>
                    <tr>
                        <th>Titre</th>
                        <td>{{ logement.titre }}</td>
                    </tr>
                    <tr>
                        <th>Description</th>
                        <td>{{ logement.description }}</td>
                    </tr>
                    <tr>
                        <th>Rating</th>
                        <td>{{ logement.rating }}</td>
                    </tr>
                    <tr>
                        <th>Capacity</th>
                        <td>{{ logement.capacity }}</td>
                    </tr>
                    <tr>
                        <th>Chambres</th>
                        <td>{{ logement.chambres }}</td>
                    </tr>
                    <tr>
                        <th>Superficie</th>
                        <td>{{ logement.superficie }}</td>
                    </tr>
                    </tbody>
                </table>

                <div class="d-flex justify-content-between align-items-center">
                    <a class="btn btn-warning" href="{{ path('app_logements_edit', {'id': logement.id}) }}">Éditer</a>
                    {{ include('logements/_delete_form.html.twig') }}
                </div>
            </div>

            <div class="col-md-6">
                <h2>Ajouter des Images</h2>
                <form method="post" action="{{ path('app_photos_new', {'id': logement.id}) }}" enctype="multipart/form-data">
                    <div class="d-flex">
                        <button type="submit" class="btn btn-success">Ajouter</button>
                    </div>
                </form>

                <h2>Photos</h2>
                <div class="row">
                    {% for photo in logement.idPhotos %}
                        <div class="col-md-4 mb-4">
                            <div class="card">
                                <img src="{{ vich_uploader_asset(photo, 'imageFile') }}" class="card-img-top"
                                     alt="Logement Photo" style="max-width: 100%; max-height: 200px;">
                                <div class="card-body">
                                    <form method="post" action="{{ path('app_photos_delete', {'id': photo.id}) }}"
                                          onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cette photo ?');">
                                        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ photo.id) }}">
                                        <button class="btn btn-danger btn-block">Supprimer</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}